services:
  # ---------- Infrastruktur ----------
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: appdb
    ports:
      - "5433:5432" # host 5433 (anti bentrok)
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks: [ecommerce-net]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    ports:
      - "8010:8080" # host 8010
    networks: [ecommerce-net]
    depends_on: [postgres]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5673:5672" # host 5673 (AMQP)
      - "15673:15672" # host 15673 (UI)
    networks: [ecommerce-net]
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ---------- Microservices ----------
  auth-service:
    build: ./services/auth-service
    environment:
      PORT: 3004
      DB_HOST: postgres
      DB_PORT: 5432 # port INTERNAL, jangan diubah
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: auth_db
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "4004:3004" # host 4004
    depends_on:
      postgres: { condition: service_healthy }
    networks: [ecommerce-net]

  product-service:
    build: ./services/product-service
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: product_db
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "4001:3001" # host 4001
    depends_on:
      postgres: { condition: service_healthy }
    networks: [ecommerce-net]

  order-service:
    build: ./services/order-service
    environment:
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: order_db
      JWT_SECRET: ${JWT_SECRET}
      PRODUCT_SERVICE_URL: http://product-service:3001 # nama+port INTERNAL
      RABBITMQ_URL: amqp://rabbitmq:5672
    ports:
      - "4002:3002" # host 4002
    depends_on:
      postgres: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }
      product-service: { condition: service_started }
    networks: [ecommerce-net]

  notification-service:
    build: ./services/notification-service
    environment:
      PORT: 3003
      RABBITMQ_URL: amqp://rabbitmq:5672
    ports:
      - "4003:3003" # host 4003
    depends_on:
      rabbitmq: { condition: service_healthy }
    networks: [ecommerce-net]

  # ---------- Frontend & Gateway ----------
  frontend:
    build: ./frontend
    networks: [ecommerce-net]

  gateway:
    image: nginx:alpine
    ports:
      - "8090:80" # host 8090 = pintu utama
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [frontend, auth-service, product-service, order-service]
    networks: [ecommerce-net]

networks:
  ecommerce-net:
    driver: bridge

volumes:
  pgdata:
